// Code generated by gen.py. DO NOT EDIT.
package esphomeproto

//go:generate ./testdata/setup.sh gen.py

const (
	AIOESPHOMEAPI_VERSION = "29.1.1"
	ESPHOME_VERSION       = "2025.2.1"
)

type MessageType int

var MessageTypeToType = map[MessageType]MessageFactory{
	MessageTypeHelloRequest:                                messageFactory[HelloRequest](),
	MessageTypeHelloResponse:                               messageFactory[HelloResponse](),
	MessageTypeConnectRequest:                              messageFactory[ConnectRequest](),
	MessageTypeConnectResponse:                             messageFactory[ConnectResponse](),
	MessageTypeDisconnectRequest:                           messageFactory[DisconnectRequest](),
	MessageTypeDisconnectResponse:                          messageFactory[DisconnectResponse](),
	MessageTypePingRequest:                                 messageFactory[PingRequest](),
	MessageTypePingResponse:                                messageFactory[PingResponse](),
	MessageTypeDeviceInfoRequest:                           messageFactory[DeviceInfoRequest](),
	MessageTypeDeviceInfoResponse:                          messageFactory[DeviceInfoResponse](),
	MessageTypeListEntitiesRequest:                         messageFactory[ListEntitiesRequest](),
	MessageTypeListEntitiesBinarySensorResponse:            messageFactory[ListEntitiesBinarySensorResponse](),
	MessageTypeListEntitiesCoverResponse:                   messageFactory[ListEntitiesCoverResponse](),
	MessageTypeListEntitiesFanResponse:                     messageFactory[ListEntitiesFanResponse](),
	MessageTypeListEntitiesLightResponse:                   messageFactory[ListEntitiesLightResponse](),
	MessageTypeListEntitiesSensorResponse:                  messageFactory[ListEntitiesSensorResponse](),
	MessageTypeListEntitiesSwitchResponse:                  messageFactory[ListEntitiesSwitchResponse](),
	MessageTypeListEntitiesTextSensorResponse:              messageFactory[ListEntitiesTextSensorResponse](),
	MessageTypeListEntitiesDoneResponse:                    messageFactory[ListEntitiesDoneResponse](),
	MessageTypeSubscribeStatesRequest:                      messageFactory[SubscribeStatesRequest](),
	MessageTypeBinarySensorStateResponse:                   messageFactory[BinarySensorStateResponse](),
	MessageTypeCoverStateResponse:                          messageFactory[CoverStateResponse](),
	MessageTypeFanStateResponse:                            messageFactory[FanStateResponse](),
	MessageTypeLightStateResponse:                          messageFactory[LightStateResponse](),
	MessageTypeSensorStateResponse:                         messageFactory[SensorStateResponse](),
	MessageTypeSwitchStateResponse:                         messageFactory[SwitchStateResponse](),
	MessageTypeTextSensorStateResponse:                     messageFactory[TextSensorStateResponse](),
	MessageTypeSubscribeLogsRequest:                        messageFactory[SubscribeLogsRequest](),
	MessageTypeSubscribeLogsResponse:                       messageFactory[SubscribeLogsResponse](),
	MessageTypeCoverCommandRequest:                         messageFactory[CoverCommandRequest](),
	MessageTypeFanCommandRequest:                           messageFactory[FanCommandRequest](),
	MessageTypeLightCommandRequest:                         messageFactory[LightCommandRequest](),
	MessageTypeSwitchCommandRequest:                        messageFactory[SwitchCommandRequest](),
	MessageTypeSubscribeHomeassistantServicesRequest:       messageFactory[SubscribeHomeassistantServicesRequest](),
	MessageTypeHomeassistantServiceResponse:                messageFactory[HomeassistantServiceResponse](),
	MessageTypeGetTimeRequest:                              messageFactory[GetTimeRequest](),
	MessageTypeGetTimeResponse:                             messageFactory[GetTimeResponse](),
	MessageTypeSubscribeHomeAssistantStatesRequest:         messageFactory[SubscribeHomeAssistantStatesRequest](),
	MessageTypeSubscribeHomeAssistantStateResponse:         messageFactory[SubscribeHomeAssistantStateResponse](),
	MessageTypeHomeAssistantStateResponse:                  messageFactory[HomeAssistantStateResponse](),
	MessageTypeListEntitiesServicesResponse:                messageFactory[ListEntitiesServicesResponse](),
	MessageTypeExecuteServiceRequest:                       messageFactory[ExecuteServiceRequest](),
	MessageTypeListEntitiesCameraResponse:                  messageFactory[ListEntitiesCameraResponse](),
	MessageTypeCameraImageResponse:                         messageFactory[CameraImageResponse](),
	MessageTypeCameraImageRequest:                          messageFactory[CameraImageRequest](),
	MessageTypeListEntitiesClimateResponse:                 messageFactory[ListEntitiesClimateResponse](),
	MessageTypeClimateStateResponse:                        messageFactory[ClimateStateResponse](),
	MessageTypeClimateCommandRequest:                       messageFactory[ClimateCommandRequest](),
	MessageTypeListEntitiesNumberResponse:                  messageFactory[ListEntitiesNumberResponse](),
	MessageTypeNumberStateResponse:                         messageFactory[NumberStateResponse](),
	MessageTypeNumberCommandRequest:                        messageFactory[NumberCommandRequest](),
	MessageTypeListEntitiesSelectResponse:                  messageFactory[ListEntitiesSelectResponse](),
	MessageTypeSelectStateResponse:                         messageFactory[SelectStateResponse](),
	MessageTypeSelectCommandRequest:                        messageFactory[SelectCommandRequest](),
	MessageTypeListEntitiesSirenResponse:                   messageFactory[ListEntitiesSirenResponse](),
	MessageTypeSirenStateResponse:                          messageFactory[SirenStateResponse](),
	MessageTypeSirenCommandRequest:                         messageFactory[SirenCommandRequest](),
	MessageTypeListEntitiesLockResponse:                    messageFactory[ListEntitiesLockResponse](),
	MessageTypeLockStateResponse:                           messageFactory[LockStateResponse](),
	MessageTypeLockCommandRequest:                          messageFactory[LockCommandRequest](),
	MessageTypeListEntitiesButtonResponse:                  messageFactory[ListEntitiesButtonResponse](),
	MessageTypeButtonCommandRequest:                        messageFactory[ButtonCommandRequest](),
	MessageTypeListEntitiesMediaPlayerResponse:             messageFactory[ListEntitiesMediaPlayerResponse](),
	MessageTypeMediaPlayerStateResponse:                    messageFactory[MediaPlayerStateResponse](),
	MessageTypeMediaPlayerCommandRequest:                   messageFactory[MediaPlayerCommandRequest](),
	MessageTypeSubscribeBluetoothLEAdvertisementsRequest:   messageFactory[SubscribeBluetoothLEAdvertisementsRequest](),
	MessageTypeBluetoothLEAdvertisementResponse:            messageFactory[BluetoothLEAdvertisementResponse](),
	MessageTypeBluetoothDeviceRequest:                      messageFactory[BluetoothDeviceRequest](),
	MessageTypeBluetoothDeviceConnectionResponse:           messageFactory[BluetoothDeviceConnectionResponse](),
	MessageTypeBluetoothGATTGetServicesRequest:             messageFactory[BluetoothGATTGetServicesRequest](),
	MessageTypeBluetoothGATTGetServicesResponse:            messageFactory[BluetoothGATTGetServicesResponse](),
	MessageTypeBluetoothGATTGetServicesDoneResponse:        messageFactory[BluetoothGATTGetServicesDoneResponse](),
	MessageTypeBluetoothGATTReadRequest:                    messageFactory[BluetoothGATTReadRequest](),
	MessageTypeBluetoothGATTReadResponse:                   messageFactory[BluetoothGATTReadResponse](),
	MessageTypeBluetoothGATTWriteRequest:                   messageFactory[BluetoothGATTWriteRequest](),
	MessageTypeBluetoothGATTReadDescriptorRequest:          messageFactory[BluetoothGATTReadDescriptorRequest](),
	MessageTypeBluetoothGATTWriteDescriptorRequest:         messageFactory[BluetoothGATTWriteDescriptorRequest](),
	MessageTypeBluetoothGATTNotifyRequest:                  messageFactory[BluetoothGATTNotifyRequest](),
	MessageTypeBluetoothGATTNotifyDataResponse:             messageFactory[BluetoothGATTNotifyDataResponse](),
	MessageTypeSubscribeBluetoothConnectionsFreeRequest:    messageFactory[SubscribeBluetoothConnectionsFreeRequest](),
	MessageTypeBluetoothConnectionsFreeResponse:            messageFactory[BluetoothConnectionsFreeResponse](),
	MessageTypeBluetoothGATTErrorResponse:                  messageFactory[BluetoothGATTErrorResponse](),
	MessageTypeBluetoothGATTWriteResponse:                  messageFactory[BluetoothGATTWriteResponse](),
	MessageTypeBluetoothGATTNotifyResponse:                 messageFactory[BluetoothGATTNotifyResponse](),
	MessageTypeBluetoothDevicePairingResponse:              messageFactory[BluetoothDevicePairingResponse](),
	MessageTypeBluetoothDeviceUnpairingResponse:            messageFactory[BluetoothDeviceUnpairingResponse](),
	MessageTypeUnsubscribeBluetoothLEAdvertisementsRequest: messageFactory[UnsubscribeBluetoothLEAdvertisementsRequest](),
	MessageTypeBluetoothDeviceClearCacheResponse:           messageFactory[BluetoothDeviceClearCacheResponse](),
	MessageTypeSubscribeVoiceAssistantRequest:              messageFactory[SubscribeVoiceAssistantRequest](),
	MessageTypeVoiceAssistantRequest:                       messageFactory[VoiceAssistantRequest](),
	MessageTypeVoiceAssistantResponse:                      messageFactory[VoiceAssistantResponse](),
	MessageTypeVoiceAssistantEventResponse:                 messageFactory[VoiceAssistantEventResponse](),
	MessageTypeBluetoothLERawAdvertisementsResponse:        messageFactory[BluetoothLERawAdvertisementsResponse](),
	MessageTypeListEntitiesAlarmControlPanelResponse:       messageFactory[ListEntitiesAlarmControlPanelResponse](),
	MessageTypeAlarmControlPanelStateResponse:              messageFactory[AlarmControlPanelStateResponse](),
	MessageTypeAlarmControlPanelCommandRequest:             messageFactory[AlarmControlPanelCommandRequest](),
	MessageTypeListEntitiesTextResponse:                    messageFactory[ListEntitiesTextResponse](),
	MessageTypeTextStateResponse:                           messageFactory[TextStateResponse](),
	MessageTypeTextCommandRequest:                          messageFactory[TextCommandRequest](),
	MessageTypeListEntitiesDateResponse:                    messageFactory[ListEntitiesDateResponse](),
	MessageTypeDateStateResponse:                           messageFactory[DateStateResponse](),
	MessageTypeDateCommandRequest:                          messageFactory[DateCommandRequest](),
	MessageTypeListEntitiesTimeResponse:                    messageFactory[ListEntitiesTimeResponse](),
	MessageTypeTimeStateResponse:                           messageFactory[TimeStateResponse](),
	MessageTypeTimeCommandRequest:                          messageFactory[TimeCommandRequest](),
	MessageTypeVoiceAssistantAudio:                         messageFactory[VoiceAssistantAudio](),
	MessageTypeListEntitiesEventResponse:                   messageFactory[ListEntitiesEventResponse](),
	MessageTypeEventResponse:                               messageFactory[EventResponse](),
	MessageTypeListEntitiesValveResponse:                   messageFactory[ListEntitiesValveResponse](),
	MessageTypeValveStateResponse:                          messageFactory[ValveStateResponse](),
	MessageTypeValveCommandRequest:                         messageFactory[ValveCommandRequest](),
	MessageTypeListEntitiesDateTimeResponse:                messageFactory[ListEntitiesDateTimeResponse](),
	MessageTypeDateTimeStateResponse:                       messageFactory[DateTimeStateResponse](),
	MessageTypeDateTimeCommandRequest:                      messageFactory[DateTimeCommandRequest](),
	MessageTypeVoiceAssistantTimerEventResponse:            messageFactory[VoiceAssistantTimerEventResponse](),
	MessageTypeListEntitiesUpdateResponse:                  messageFactory[ListEntitiesUpdateResponse](),
	MessageTypeUpdateStateResponse:                         messageFactory[UpdateStateResponse](),
	MessageTypeUpdateCommandRequest:                        messageFactory[UpdateCommandRequest](),
	MessageTypeVoiceAssistantAnnounceRequest:               messageFactory[VoiceAssistantAnnounceRequest](),
	MessageTypeVoiceAssistantAnnounceFinished:              messageFactory[VoiceAssistantAnnounceFinished](),
	MessageTypeVoiceAssistantConfigurationRequest:          messageFactory[VoiceAssistantConfigurationRequest](),
	MessageTypeVoiceAssistantConfigurationResponse:         messageFactory[VoiceAssistantConfigurationResponse](),
	MessageTypeVoiceAssistantSetConfiguration:              messageFactory[VoiceAssistantSetConfiguration](),
}

const MessageTypeHelloRequest MessageType = 1

func (x *HelloRequest) EsphomeMessageType() MessageType { return MessageTypeHelloRequest }
func (x *HelloRequest) EsphomeSource() APISourceType    { return APISourceType(2) }

const MessageTypeHelloResponse MessageType = 2

func (x *HelloResponse) EsphomeMessageType() MessageType { return MessageTypeHelloResponse }
func (x *HelloResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeConnectRequest MessageType = 3

func (x *ConnectRequest) EsphomeMessageType() MessageType { return MessageTypeConnectRequest }
func (x *ConnectRequest) EsphomeSource() APISourceType    { return APISourceType(2) }

const MessageTypeConnectResponse MessageType = 4

func (x *ConnectResponse) EsphomeMessageType() MessageType { return MessageTypeConnectResponse }
func (x *ConnectResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeDisconnectRequest MessageType = 5

func (x *DisconnectRequest) EsphomeMessageType() MessageType { return MessageTypeDisconnectRequest }
func (x *DisconnectRequest) EsphomeSource() APISourceType    { return APISourceType(0) }

const MessageTypeDisconnectResponse MessageType = 6

func (x *DisconnectResponse) EsphomeMessageType() MessageType { return MessageTypeDisconnectResponse }
func (x *DisconnectResponse) EsphomeSource() APISourceType    { return APISourceType(0) }

const MessageTypePingRequest MessageType = 7

func (x *PingRequest) EsphomeMessageType() MessageType { return MessageTypePingRequest }
func (x *PingRequest) EsphomeSource() APISourceType    { return APISourceType(0) }

const MessageTypePingResponse MessageType = 8

func (x *PingResponse) EsphomeMessageType() MessageType { return MessageTypePingResponse }
func (x *PingResponse) EsphomeSource() APISourceType    { return APISourceType(0) }

const MessageTypeDeviceInfoRequest MessageType = 9

func (x *DeviceInfoRequest) EsphomeMessageType() MessageType { return MessageTypeDeviceInfoRequest }
func (x *DeviceInfoRequest) EsphomeSource() APISourceType    { return APISourceType(2) }

const MessageTypeDeviceInfoResponse MessageType = 10

func (x *DeviceInfoResponse) EsphomeMessageType() MessageType { return MessageTypeDeviceInfoResponse }
func (x *DeviceInfoResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeListEntitiesRequest MessageType = 11

func (x *ListEntitiesRequest) EsphomeMessageType() MessageType { return MessageTypeListEntitiesRequest }
func (x *ListEntitiesRequest) EsphomeSource() APISourceType    { return APISourceType(2) }

const MessageTypeListEntitiesBinarySensorResponse MessageType = 12

func (x *ListEntitiesBinarySensorResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesBinarySensorResponse
}
func (x *ListEntitiesBinarySensorResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeListEntitiesCoverResponse MessageType = 13

func (x *ListEntitiesCoverResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesCoverResponse
}
func (x *ListEntitiesCoverResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeListEntitiesFanResponse MessageType = 14

func (x *ListEntitiesFanResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesFanResponse
}
func (x *ListEntitiesFanResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeListEntitiesLightResponse MessageType = 15

func (x *ListEntitiesLightResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesLightResponse
}
func (x *ListEntitiesLightResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeListEntitiesSensorResponse MessageType = 16

func (x *ListEntitiesSensorResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesSensorResponse
}
func (x *ListEntitiesSensorResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeListEntitiesSwitchResponse MessageType = 17

func (x *ListEntitiesSwitchResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesSwitchResponse
}
func (x *ListEntitiesSwitchResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeListEntitiesTextSensorResponse MessageType = 18

func (x *ListEntitiesTextSensorResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesTextSensorResponse
}
func (x *ListEntitiesTextSensorResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeListEntitiesDoneResponse MessageType = 19

func (x *ListEntitiesDoneResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesDoneResponse
}
func (x *ListEntitiesDoneResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeSubscribeStatesRequest MessageType = 20

func (x *SubscribeStatesRequest) EsphomeMessageType() MessageType {
	return MessageTypeSubscribeStatesRequest
}
func (x *SubscribeStatesRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeBinarySensorStateResponse MessageType = 21

func (x *BinarySensorStateResponse) EsphomeMessageType() MessageType {
	return MessageTypeBinarySensorStateResponse
}
func (x *BinarySensorStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeCoverStateResponse MessageType = 22

func (x *CoverStateResponse) EsphomeMessageType() MessageType { return MessageTypeCoverStateResponse }
func (x *CoverStateResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeFanStateResponse MessageType = 23

func (x *FanStateResponse) EsphomeMessageType() MessageType { return MessageTypeFanStateResponse }
func (x *FanStateResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeLightStateResponse MessageType = 24

func (x *LightStateResponse) EsphomeMessageType() MessageType { return MessageTypeLightStateResponse }
func (x *LightStateResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeSensorStateResponse MessageType = 25

func (x *SensorStateResponse) EsphomeMessageType() MessageType { return MessageTypeSensorStateResponse }
func (x *SensorStateResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeSwitchStateResponse MessageType = 26

func (x *SwitchStateResponse) EsphomeMessageType() MessageType { return MessageTypeSwitchStateResponse }
func (x *SwitchStateResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeTextSensorStateResponse MessageType = 27

func (x *TextSensorStateResponse) EsphomeMessageType() MessageType {
	return MessageTypeTextSensorStateResponse
}
func (x *TextSensorStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeSubscribeLogsRequest MessageType = 28

func (x *SubscribeLogsRequest) EsphomeMessageType() MessageType {
	return MessageTypeSubscribeLogsRequest
}
func (x *SubscribeLogsRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeSubscribeLogsResponse MessageType = 29

func (x *SubscribeLogsResponse) EsphomeMessageType() MessageType {
	return MessageTypeSubscribeLogsResponse
}
func (x *SubscribeLogsResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeCoverCommandRequest MessageType = 30

func (x *CoverCommandRequest) EsphomeMessageType() MessageType { return MessageTypeCoverCommandRequest }
func (x *CoverCommandRequest) EsphomeSource() APISourceType    { return APISourceType(2) }

const MessageTypeFanCommandRequest MessageType = 31

func (x *FanCommandRequest) EsphomeMessageType() MessageType { return MessageTypeFanCommandRequest }
func (x *FanCommandRequest) EsphomeSource() APISourceType    { return APISourceType(2) }

const MessageTypeLightCommandRequest MessageType = 32

func (x *LightCommandRequest) EsphomeMessageType() MessageType { return MessageTypeLightCommandRequest }
func (x *LightCommandRequest) EsphomeSource() APISourceType    { return APISourceType(2) }

const MessageTypeSwitchCommandRequest MessageType = 33

func (x *SwitchCommandRequest) EsphomeMessageType() MessageType {
	return MessageTypeSwitchCommandRequest
}
func (x *SwitchCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeSubscribeHomeassistantServicesRequest MessageType = 34

func (x *SubscribeHomeassistantServicesRequest) EsphomeMessageType() MessageType {
	return MessageTypeSubscribeHomeassistantServicesRequest
}
func (x *SubscribeHomeassistantServicesRequest) EsphomeSource() APISourceType {
	return APISourceType(2)
}

const MessageTypeHomeassistantServiceResponse MessageType = 35

func (x *HomeassistantServiceResponse) EsphomeMessageType() MessageType {
	return MessageTypeHomeassistantServiceResponse
}
func (x *HomeassistantServiceResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeGetTimeRequest MessageType = 36

func (x *GetTimeRequest) EsphomeMessageType() MessageType { return MessageTypeGetTimeRequest }
func (x *GetTimeRequest) EsphomeSource() APISourceType    { return APISourceType(0) }

const MessageTypeGetTimeResponse MessageType = 37

func (x *GetTimeResponse) EsphomeMessageType() MessageType { return MessageTypeGetTimeResponse }
func (x *GetTimeResponse) EsphomeSource() APISourceType    { return APISourceType(0) }

const MessageTypeSubscribeHomeAssistantStatesRequest MessageType = 38

func (x *SubscribeHomeAssistantStatesRequest) EsphomeMessageType() MessageType {
	return MessageTypeSubscribeHomeAssistantStatesRequest
}
func (x *SubscribeHomeAssistantStatesRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeSubscribeHomeAssistantStateResponse MessageType = 39

func (x *SubscribeHomeAssistantStateResponse) EsphomeMessageType() MessageType {
	return MessageTypeSubscribeHomeAssistantStateResponse
}
func (x *SubscribeHomeAssistantStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeHomeAssistantStateResponse MessageType = 40

func (x *HomeAssistantStateResponse) EsphomeMessageType() MessageType {
	return MessageTypeHomeAssistantStateResponse
}
func (x *HomeAssistantStateResponse) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeListEntitiesServicesResponse MessageType = 41

func (x *ListEntitiesServicesResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesServicesResponse
}
func (x *ListEntitiesServicesResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeExecuteServiceRequest MessageType = 42

func (x *ExecuteServiceRequest) EsphomeMessageType() MessageType {
	return MessageTypeExecuteServiceRequest
}
func (x *ExecuteServiceRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeListEntitiesCameraResponse MessageType = 43

func (x *ListEntitiesCameraResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesCameraResponse
}
func (x *ListEntitiesCameraResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeCameraImageResponse MessageType = 44

func (x *CameraImageResponse) EsphomeMessageType() MessageType { return MessageTypeCameraImageResponse }
func (x *CameraImageResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeCameraImageRequest MessageType = 45

func (x *CameraImageRequest) EsphomeMessageType() MessageType { return MessageTypeCameraImageRequest }
func (x *CameraImageRequest) EsphomeSource() APISourceType    { return APISourceType(2) }

const MessageTypeListEntitiesClimateResponse MessageType = 46

func (x *ListEntitiesClimateResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesClimateResponse
}
func (x *ListEntitiesClimateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeClimateStateResponse MessageType = 47

func (x *ClimateStateResponse) EsphomeMessageType() MessageType {
	return MessageTypeClimateStateResponse
}
func (x *ClimateStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeClimateCommandRequest MessageType = 48

func (x *ClimateCommandRequest) EsphomeMessageType() MessageType {
	return MessageTypeClimateCommandRequest
}
func (x *ClimateCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeListEntitiesNumberResponse MessageType = 49

func (x *ListEntitiesNumberResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesNumberResponse
}
func (x *ListEntitiesNumberResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeNumberStateResponse MessageType = 50

func (x *NumberStateResponse) EsphomeMessageType() MessageType { return MessageTypeNumberStateResponse }
func (x *NumberStateResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeNumberCommandRequest MessageType = 51

func (x *NumberCommandRequest) EsphomeMessageType() MessageType {
	return MessageTypeNumberCommandRequest
}
func (x *NumberCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeListEntitiesSelectResponse MessageType = 52

func (x *ListEntitiesSelectResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesSelectResponse
}
func (x *ListEntitiesSelectResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeSelectStateResponse MessageType = 53

func (x *SelectStateResponse) EsphomeMessageType() MessageType { return MessageTypeSelectStateResponse }
func (x *SelectStateResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeSelectCommandRequest MessageType = 54

func (x *SelectCommandRequest) EsphomeMessageType() MessageType {
	return MessageTypeSelectCommandRequest
}
func (x *SelectCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeListEntitiesSirenResponse MessageType = 55

func (x *ListEntitiesSirenResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesSirenResponse
}
func (x *ListEntitiesSirenResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeSirenStateResponse MessageType = 56

func (x *SirenStateResponse) EsphomeMessageType() MessageType { return MessageTypeSirenStateResponse }
func (x *SirenStateResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeSirenCommandRequest MessageType = 57

func (x *SirenCommandRequest) EsphomeMessageType() MessageType { return MessageTypeSirenCommandRequest }
func (x *SirenCommandRequest) EsphomeSource() APISourceType    { return APISourceType(2) }

const MessageTypeListEntitiesLockResponse MessageType = 58

func (x *ListEntitiesLockResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesLockResponse
}
func (x *ListEntitiesLockResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeLockStateResponse MessageType = 59

func (x *LockStateResponse) EsphomeMessageType() MessageType { return MessageTypeLockStateResponse }
func (x *LockStateResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeLockCommandRequest MessageType = 60

func (x *LockCommandRequest) EsphomeMessageType() MessageType { return MessageTypeLockCommandRequest }
func (x *LockCommandRequest) EsphomeSource() APISourceType    { return APISourceType(2) }

const MessageTypeListEntitiesButtonResponse MessageType = 61

func (x *ListEntitiesButtonResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesButtonResponse
}
func (x *ListEntitiesButtonResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeButtonCommandRequest MessageType = 62

func (x *ButtonCommandRequest) EsphomeMessageType() MessageType {
	return MessageTypeButtonCommandRequest
}
func (x *ButtonCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeListEntitiesMediaPlayerResponse MessageType = 63

func (x *ListEntitiesMediaPlayerResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesMediaPlayerResponse
}
func (x *ListEntitiesMediaPlayerResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeMediaPlayerStateResponse MessageType = 64

func (x *MediaPlayerStateResponse) EsphomeMessageType() MessageType {
	return MessageTypeMediaPlayerStateResponse
}
func (x *MediaPlayerStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeMediaPlayerCommandRequest MessageType = 65

func (x *MediaPlayerCommandRequest) EsphomeMessageType() MessageType {
	return MessageTypeMediaPlayerCommandRequest
}
func (x *MediaPlayerCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeSubscribeBluetoothLEAdvertisementsRequest MessageType = 66

func (x *SubscribeBluetoothLEAdvertisementsRequest) EsphomeMessageType() MessageType {
	return MessageTypeSubscribeBluetoothLEAdvertisementsRequest
}
func (x *SubscribeBluetoothLEAdvertisementsRequest) EsphomeSource() APISourceType {
	return APISourceType(2)
}

const MessageTypeBluetoothLEAdvertisementResponse MessageType = 67

func (x *BluetoothLEAdvertisementResponse) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothLEAdvertisementResponse
}
func (x *BluetoothLEAdvertisementResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeBluetoothDeviceRequest MessageType = 68

func (x *BluetoothDeviceRequest) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothDeviceRequest
}
func (x *BluetoothDeviceRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeBluetoothDeviceConnectionResponse MessageType = 69

func (x *BluetoothDeviceConnectionResponse) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothDeviceConnectionResponse
}
func (x *BluetoothDeviceConnectionResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeBluetoothGATTGetServicesRequest MessageType = 70

func (x *BluetoothGATTGetServicesRequest) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothGATTGetServicesRequest
}
func (x *BluetoothGATTGetServicesRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeBluetoothGATTGetServicesResponse MessageType = 71

func (x *BluetoothGATTGetServicesResponse) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothGATTGetServicesResponse
}
func (x *BluetoothGATTGetServicesResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeBluetoothGATTGetServicesDoneResponse MessageType = 72

func (x *BluetoothGATTGetServicesDoneResponse) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothGATTGetServicesDoneResponse
}
func (x *BluetoothGATTGetServicesDoneResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeBluetoothGATTReadRequest MessageType = 73

func (x *BluetoothGATTReadRequest) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothGATTReadRequest
}
func (x *BluetoothGATTReadRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeBluetoothGATTReadResponse MessageType = 74

func (x *BluetoothGATTReadResponse) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothGATTReadResponse
}
func (x *BluetoothGATTReadResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeBluetoothGATTWriteRequest MessageType = 75

func (x *BluetoothGATTWriteRequest) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothGATTWriteRequest
}
func (x *BluetoothGATTWriteRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeBluetoothGATTReadDescriptorRequest MessageType = 76

func (x *BluetoothGATTReadDescriptorRequest) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothGATTReadDescriptorRequest
}
func (x *BluetoothGATTReadDescriptorRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeBluetoothGATTWriteDescriptorRequest MessageType = 77

func (x *BluetoothGATTWriteDescriptorRequest) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothGATTWriteDescriptorRequest
}
func (x *BluetoothGATTWriteDescriptorRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeBluetoothGATTNotifyRequest MessageType = 78

func (x *BluetoothGATTNotifyRequest) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothGATTNotifyRequest
}
func (x *BluetoothGATTNotifyRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeBluetoothGATTNotifyDataResponse MessageType = 79

func (x *BluetoothGATTNotifyDataResponse) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothGATTNotifyDataResponse
}
func (x *BluetoothGATTNotifyDataResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeSubscribeBluetoothConnectionsFreeRequest MessageType = 80

func (x *SubscribeBluetoothConnectionsFreeRequest) EsphomeMessageType() MessageType {
	return MessageTypeSubscribeBluetoothConnectionsFreeRequest
}
func (x *SubscribeBluetoothConnectionsFreeRequest) EsphomeSource() APISourceType {
	return APISourceType(2)
}

const MessageTypeBluetoothConnectionsFreeResponse MessageType = 81

func (x *BluetoothConnectionsFreeResponse) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothConnectionsFreeResponse
}
func (x *BluetoothConnectionsFreeResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeBluetoothGATTErrorResponse MessageType = 82

func (x *BluetoothGATTErrorResponse) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothGATTErrorResponse
}
func (x *BluetoothGATTErrorResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeBluetoothGATTWriteResponse MessageType = 83

func (x *BluetoothGATTWriteResponse) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothGATTWriteResponse
}
func (x *BluetoothGATTWriteResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeBluetoothGATTNotifyResponse MessageType = 84

func (x *BluetoothGATTNotifyResponse) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothGATTNotifyResponse
}
func (x *BluetoothGATTNotifyResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeBluetoothDevicePairingResponse MessageType = 85

func (x *BluetoothDevicePairingResponse) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothDevicePairingResponse
}
func (x *BluetoothDevicePairingResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeBluetoothDeviceUnpairingResponse MessageType = 86

func (x *BluetoothDeviceUnpairingResponse) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothDeviceUnpairingResponse
}
func (x *BluetoothDeviceUnpairingResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeUnsubscribeBluetoothLEAdvertisementsRequest MessageType = 87

func (x *UnsubscribeBluetoothLEAdvertisementsRequest) EsphomeMessageType() MessageType {
	return MessageTypeUnsubscribeBluetoothLEAdvertisementsRequest
}
func (x *UnsubscribeBluetoothLEAdvertisementsRequest) EsphomeSource() APISourceType {
	return APISourceType(2)
}

const MessageTypeBluetoothDeviceClearCacheResponse MessageType = 88

func (x *BluetoothDeviceClearCacheResponse) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothDeviceClearCacheResponse
}
func (x *BluetoothDeviceClearCacheResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeSubscribeVoiceAssistantRequest MessageType = 89

func (x *SubscribeVoiceAssistantRequest) EsphomeMessageType() MessageType {
	return MessageTypeSubscribeVoiceAssistantRequest
}
func (x *SubscribeVoiceAssistantRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeVoiceAssistantRequest MessageType = 90

func (x *VoiceAssistantRequest) EsphomeMessageType() MessageType {
	return MessageTypeVoiceAssistantRequest
}
func (x *VoiceAssistantRequest) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeVoiceAssistantResponse MessageType = 91

func (x *VoiceAssistantResponse) EsphomeMessageType() MessageType {
	return MessageTypeVoiceAssistantResponse
}
func (x *VoiceAssistantResponse) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeVoiceAssistantEventResponse MessageType = 92

func (x *VoiceAssistantEventResponse) EsphomeMessageType() MessageType {
	return MessageTypeVoiceAssistantEventResponse
}
func (x *VoiceAssistantEventResponse) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeBluetoothLERawAdvertisementsResponse MessageType = 93

func (x *BluetoothLERawAdvertisementsResponse) EsphomeMessageType() MessageType {
	return MessageTypeBluetoothLERawAdvertisementsResponse
}
func (x *BluetoothLERawAdvertisementsResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeListEntitiesAlarmControlPanelResponse MessageType = 94

func (x *ListEntitiesAlarmControlPanelResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesAlarmControlPanelResponse
}
func (x *ListEntitiesAlarmControlPanelResponse) EsphomeSource() APISourceType {
	return APISourceType(1)
}

const MessageTypeAlarmControlPanelStateResponse MessageType = 95

func (x *AlarmControlPanelStateResponse) EsphomeMessageType() MessageType {
	return MessageTypeAlarmControlPanelStateResponse
}
func (x *AlarmControlPanelStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeAlarmControlPanelCommandRequest MessageType = 96

func (x *AlarmControlPanelCommandRequest) EsphomeMessageType() MessageType {
	return MessageTypeAlarmControlPanelCommandRequest
}
func (x *AlarmControlPanelCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeListEntitiesTextResponse MessageType = 97

func (x *ListEntitiesTextResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesTextResponse
}
func (x *ListEntitiesTextResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeTextStateResponse MessageType = 98

func (x *TextStateResponse) EsphomeMessageType() MessageType { return MessageTypeTextStateResponse }
func (x *TextStateResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeTextCommandRequest MessageType = 99

func (x *TextCommandRequest) EsphomeMessageType() MessageType { return MessageTypeTextCommandRequest }
func (x *TextCommandRequest) EsphomeSource() APISourceType    { return APISourceType(2) }

const MessageTypeListEntitiesDateResponse MessageType = 100

func (x *ListEntitiesDateResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesDateResponse
}
func (x *ListEntitiesDateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeDateStateResponse MessageType = 101

func (x *DateStateResponse) EsphomeMessageType() MessageType { return MessageTypeDateStateResponse }
func (x *DateStateResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeDateCommandRequest MessageType = 102

func (x *DateCommandRequest) EsphomeMessageType() MessageType { return MessageTypeDateCommandRequest }
func (x *DateCommandRequest) EsphomeSource() APISourceType    { return APISourceType(2) }

const MessageTypeListEntitiesTimeResponse MessageType = 103

func (x *ListEntitiesTimeResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesTimeResponse
}
func (x *ListEntitiesTimeResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeTimeStateResponse MessageType = 104

func (x *TimeStateResponse) EsphomeMessageType() MessageType { return MessageTypeTimeStateResponse }
func (x *TimeStateResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeTimeCommandRequest MessageType = 105

func (x *TimeCommandRequest) EsphomeMessageType() MessageType { return MessageTypeTimeCommandRequest }
func (x *TimeCommandRequest) EsphomeSource() APISourceType    { return APISourceType(2) }

const MessageTypeVoiceAssistantAudio MessageType = 106

func (x *VoiceAssistantAudio) EsphomeMessageType() MessageType { return MessageTypeVoiceAssistantAudio }
func (x *VoiceAssistantAudio) EsphomeSource() APISourceType    { return APISourceType(0) }

const MessageTypeListEntitiesEventResponse MessageType = 107

func (x *ListEntitiesEventResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesEventResponse
}
func (x *ListEntitiesEventResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeEventResponse MessageType = 108

func (x *EventResponse) EsphomeMessageType() MessageType { return MessageTypeEventResponse }
func (x *EventResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeListEntitiesValveResponse MessageType = 109

func (x *ListEntitiesValveResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesValveResponse
}
func (x *ListEntitiesValveResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeValveStateResponse MessageType = 110

func (x *ValveStateResponse) EsphomeMessageType() MessageType { return MessageTypeValveStateResponse }
func (x *ValveStateResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeValveCommandRequest MessageType = 111

func (x *ValveCommandRequest) EsphomeMessageType() MessageType { return MessageTypeValveCommandRequest }
func (x *ValveCommandRequest) EsphomeSource() APISourceType    { return APISourceType(2) }

const MessageTypeListEntitiesDateTimeResponse MessageType = 112

func (x *ListEntitiesDateTimeResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesDateTimeResponse
}
func (x *ListEntitiesDateTimeResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeDateTimeStateResponse MessageType = 113

func (x *DateTimeStateResponse) EsphomeMessageType() MessageType {
	return MessageTypeDateTimeStateResponse
}
func (x *DateTimeStateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeDateTimeCommandRequest MessageType = 114

func (x *DateTimeCommandRequest) EsphomeMessageType() MessageType {
	return MessageTypeDateTimeCommandRequest
}
func (x *DateTimeCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeVoiceAssistantTimerEventResponse MessageType = 115

func (x *VoiceAssistantTimerEventResponse) EsphomeMessageType() MessageType {
	return MessageTypeVoiceAssistantTimerEventResponse
}
func (x *VoiceAssistantTimerEventResponse) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeListEntitiesUpdateResponse MessageType = 116

func (x *ListEntitiesUpdateResponse) EsphomeMessageType() MessageType {
	return MessageTypeListEntitiesUpdateResponse
}
func (x *ListEntitiesUpdateResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeUpdateStateResponse MessageType = 117

func (x *UpdateStateResponse) EsphomeMessageType() MessageType { return MessageTypeUpdateStateResponse }
func (x *UpdateStateResponse) EsphomeSource() APISourceType    { return APISourceType(1) }

const MessageTypeUpdateCommandRequest MessageType = 118

func (x *UpdateCommandRequest) EsphomeMessageType() MessageType {
	return MessageTypeUpdateCommandRequest
}
func (x *UpdateCommandRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeVoiceAssistantAnnounceRequest MessageType = 119

func (x *VoiceAssistantAnnounceRequest) EsphomeMessageType() MessageType {
	return MessageTypeVoiceAssistantAnnounceRequest
}
func (x *VoiceAssistantAnnounceRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeVoiceAssistantAnnounceFinished MessageType = 120

func (x *VoiceAssistantAnnounceFinished) EsphomeMessageType() MessageType {
	return MessageTypeVoiceAssistantAnnounceFinished
}
func (x *VoiceAssistantAnnounceFinished) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeVoiceAssistantConfigurationRequest MessageType = 121

func (x *VoiceAssistantConfigurationRequest) EsphomeMessageType() MessageType {
	return MessageTypeVoiceAssistantConfigurationRequest
}
func (x *VoiceAssistantConfigurationRequest) EsphomeSource() APISourceType { return APISourceType(2) }

const MessageTypeVoiceAssistantConfigurationResponse MessageType = 122

func (x *VoiceAssistantConfigurationResponse) EsphomeMessageType() MessageType {
	return MessageTypeVoiceAssistantConfigurationResponse
}
func (x *VoiceAssistantConfigurationResponse) EsphomeSource() APISourceType { return APISourceType(1) }

const MessageTypeVoiceAssistantSetConfiguration MessageType = 123

func (x *VoiceAssistantSetConfiguration) EsphomeMessageType() MessageType {
	return MessageTypeVoiceAssistantSetConfiguration
}
func (x *VoiceAssistantSetConfiguration) EsphomeSource() APISourceType { return APISourceType(2) }
